### ISSUE TITLE
Widget date bug 

### ISSUE THREAD

**Issue by Robinsonpardo** [deivids84/HyperOS-XML-1.0-SPANISH#3]
Updated Zeus, it mostly works ok, it only has a bug on the lock screen, the date of the month, in the first digit, is 6 instead of 0 and 7 instead of 1.
![Screenshot_2024-03-10-04-10-28-145_lockscreen](https://github.com/deivids84/HyperOS-XML-1.0-SPANISH/assets/162884975/f5a85e5e-8292-47a3-b625-92c2388c9414)

**Comment by tobas2** [comment]
Same on shennong Xiaomi 14 Pro. Date on lockscreen shows 3/71 instead of 11/3. Thanks devs and translators!

**Comment by deivids84** [comment]
¿Esto les pasa con español de España?

**Comment by Robinsonpardo** [comment]
Español (América)

**Comment by deivids84** [comment]
Ok. Corregido.

**Comment by Robinsonpardo** [comment]
Muchas gracias 👍🏼🙌🏼

**Comment by tobas2** [comment]
Muchas gracias!

**Comment by tobas2** [comment]
Hola! El error sigue en el ROM del día de hoy.

![Screenshot_2024-03-16-13-49-46-120_lockscreen](https://github.com/deivids84/HyperOS-XML-1.0-SPANISH/assets/121220245/cbfe61e6-9ee9-409c-93fd-b75cedae7036)

**Comment by Robinsonpardo** [comment]
Sí confirmo, en español (América) aún persiste. Cambia el idioma a español (España) mientras tanto

**Comment by tobas2** [comment]
> Ok. Corregido.

Que tal. Aún persiste el problema en el último Weekly ROM para Español (América)

Saludos, gracias!

![Screenshot_2024-03-21-19-49-49-305_lockscreen](https://github.com/deivids84/HyperOS-XML-1.0-SPANISH/assets/121220245/89dbdb0a-de4f-406c-9810-369896fb7805)

**Comment by ingbrzy** [comment]
fixed
